/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   history-panel.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />
/// <reference path="../iron-flex-layout/iron-flex-layout.d.ts" />
/// <reference path="../paper-button/paper-button.d.ts" />
/// <reference path="../iron-icon/iron-icon.d.ts" />
/// <reference path="../arc-icons/arc-icons.d.ts" />
/// <reference path="../paper-menu-button/paper-menu-button.d.ts" />
/// <reference path="../paper-icon-button/paper-icon-button.d.ts" />
/// <reference path="../paper-listbox/paper-listbox.d.ts" />
/// <reference path="../paper-item/paper-icon-item.d.ts" />
/// <reference path="../paper-progress/paper-progress.d.ts" />
/// <reference path="../paper-toast/paper-toast.d.ts" />
/// <reference path="../paper-dialog/paper-dialog.d.ts" />
/// <reference path="../bottom-sheet/bottom-sheet.d.ts" />
/// <reference path="../saved-request-detail/saved-request-detail.d.ts" />
/// <reference path="../saved-request-editor/saved-request-editor.d.ts" />
/// <reference path="../requests-list-mixin/requests-list-mixin.d.ts" />
/// <reference path="../paper-fab/paper-fab.d.ts" />
/// <reference path="../paper-input/paper-input.d.ts" />
/// <reference path="../history-list-mixin/history-list-mixin.d.ts" />
/// <reference path="history-panel-list.d.ts" />

declare namespace UiElements {

  /**
   * History panel screen for Advanced REST Client.
   *
   * ### Styling
   * `<history-panel>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--history-panel` | Mixin applied to the element | `{}`
   * `--arc-font-headline` | Mixin applied to the header | `{}`
   * `--arc-font-subhead` | Mixin applied to the subheader | `{}`
   * `--history-panel-loader` | Mixin applied to the loader element | `{}`
   * `--history-panel-list` | Mixin apllied to the list element | `{}`
   * `--history-panel-toast-revert-button` | Mixin appllied to the rever button | `{}`
   * `--warning-primary-color` | Main color of the warning messages | `#FF7043`
   * `--warning-contrast-color` | Contrast color for the warning color | `#fff`
   * `--error-toast` | Mixin applied to the error toast | `{}`
   * `--empty-info` | Mixin applied to the label rendered when no data is available. | `{}`
   * `--history-panel-fab-background-color` | Bg color of fab button | `--primary-color`
   * `--history-panel-bottom-sheet` | Mixin apllied to the `<bottom-sheet>` elements | `{}`
   */
  class HistoryPanel extends
    ArcComponents.RequestsListMixin(
    ArcComponents.HistoryListMixin(
    Object)) {

    /**
     * List of requests that has been recently removed
     */
    _latestDeleted: any[]|null|undefined;

    /**
     * Computed value, true if the requests lists is hidden.
     */
    readonly listHidden: boolean|null|undefined;

    /**
     * Selected items list.
     */
    selectedItems: Array<object|null>|null;

    /**
     * Computed value, true when the user made a selection on the list.
     */
    readonly hasSelection: boolean|null|undefined;

    /**
     * When true the editor panel is rendered
     */
    editorOpened: boolean|null|undefined;

    /**
     * When true the details panel is rendered
     */
    detailsOpened: boolean|null|undefined;
    connectedCallback(): void;
    disconnectedCallback(): void;

    /**
     * Notifies the list that the resize event occurred.
     * Should be called whhen content of the list changed but the list wasn't
     * visible at the time.
     */
    notifyResize(): void;

    /**
     * Computes value of the `listHidden` property.
     * List is hidden when no requests are found and it is not searching.
     */
    _computeListHidden(hasRequests: Boolean|null, isSearch: Boolean|null): Boolean|null;

    /**
     * Handler for navigate action from the list
     */
    _navigateHandler(): void;

    /**
     * Handles items delete event.
     */
    _deleteSelected(): any;

    /**
     * Deletes a request from the details panel.
     */
    _deleteRequestDetails(): any;

    /**
     * Performs a delete action of request items.
     *
     * @param deleted List of deleted items.
     * @returns [description]
     */
    _delete(deleted: Array<object|null>|null): any;

    /**
     * Restores removed requests.
     * It does nothing if `_latestDeleted` is not set or empty.
     *
     * @returns A promise resolved when objects were restored
     */
    revertDeleted(): Promise<any>|null;

    /**
     * Forces selection menu to close.
     */
    _closeSelectionMenu(): void;

    /**
     * Calles `_exportItems()` with default destination (`file`)
     */
    _exportSelected(): void;

    /**
     * Calles `_exportItems()` with destination set to `drive`
     */
    _exportSelectedDrive(): void;

    /**
     * Forces main menu to close.
     */
    _closeMainMenu(): void;

    /**
     * Menu handler to export all project data to Drive
     */
    _onExportAllDrive(): void;

    /**
     * Menu handler to export all project data to file
     */
    _onExportAll(): void;

    /**
     * Requests application to export all data to `destination`.
     * This works with `arc-data-export` element.
     *
     * @param destination One of the supporting destinations
     * in `arc-data-export`.
     */
    _exportAll(destination: String|null): void;

    /**
     * Dispatches the `export-project` event with relevant data.
     */
    _exportItems(destination: String|null): void;

    /**
     * Opens the request details applet with the request.
     */
    _onDetails(e: CustomEvent|null): void;

    /**
     * Fires `navigate` event for currently loaded in the details request.
     */
    _loadRequestDetails(): void;
    _searchHandler(e: any): void;

    /**
     * Handler for delete all menu option click.
     */
    _deleteAllClick(): void;

    /**
     * Called when delete datastore dialog is closed.
     */
    _onClearDialogResult(e: CustomEvent|null): void;

    /**
     * Removes all data from the datastore and then fires
     */
    _clearDatastore(): void;

    /**
     * Opens request details editor in place of the request details applet.
     */
    _editRequestDetails(): void;
    _resizeSheetContent(e: any): void;
    _cancelRequestEdit(): void;

    /**
     * Handler fro save request event from the editor.
     */
    _saveRequestEdit(): void;
    _computeHasSelection(length: any): any;
  }
}

interface HTMLElementTagNameMap {
  "history-panel": UiElements.HistoryPanel;
}
