/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   src/HistoryPanelList.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {LitElement, html, css} from 'lit-element';

import {AnypointMenuMixin} from '@anypoint-web-components/anypoint-menu-mixin/anypoint-menu-mixin.js';

export {HistoryPanelListWrapper};

declare class HistoryPanelListWrapper {
  render(): any;
}

export {HistoryPanelList};

declare namespace ApiElements {

  /**
   * `history-panel-list`
   */
  class HistoryPanelList extends LitElement {
    readonly _list: any;

    /**
     * List of selected items on the list.
     */
    selectedItems: any[]|null|undefined;
    requests: any[]|null|undefined;
    selectedIndexes: any[]|null|undefined;
    hasTwoLines: boolean|null|undefined;

    /**
     * Enables the comonent to accept drop action with a request.
     */
    draggableEnabled: boolean|null|undefined;
    constructor();
    connectedCallback(): void;
    disconnectedCallback(): void;
    render(): any;
    _listTemplate(): any;
    clearSelection(): void;

    /**
     * Called every time the element changed it's scroll position. It will call the `makeQuery`
     * function when there's less than 120px left to scroll. (also it must be opened and must not
     * already querying).
     */
    _scrollHandler(): void;
    loadNext(): void;
    _requestDetails(e: any): void;
    _navigateItem(e: any): void;
    _selectedHandler(e: any): void;

    /**
     * Handler for the `dragstart` event added to the list item when `draggableEnabled`
     * is set to true.
     * This function sets request data on the `dataTransfer` object with `arc/request-object`
     * mime type. The request data is a serialized JSON with request model.
     */
    _dragStart(e: Event|null): void;
  }
}
